server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA 라우팅 설정
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 기본 보안 헤더
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    # Content Security Policy (CSP)
    add_header Content-Security-Policy "script-src 'self' 'nonce-unique-nonce-value' 'unsafe-inline'; object-src 'none'; base-uri 'self';";

    # 요청 및 오류 로그 설정
    error_log /var/log/nginx/error.log debug;

    # 정적 파일 캐싱 설정
    location /assets {
        expires 1y;
        add_header Cache-Control "public";
    }

    # gzip 압축 설정
    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
    gzip_min_length 1000;
}