export const CALL_API = {
  GET_WEBSOCKET_URL: '/api/v1/call',
  DEFAULT_SERVER_ID: '1',
  DEFAULT_VOICE_CHANNEL_ID: '1',
  DEFAULT_VIDEO_CHANNEL_ID: '2',
};

export const OP_CODES = {
  INITIAL: 0,
  INITIAL_ACK: 10,
  HEARTBEAT: 1,
  HEARTBEAT_ACK: 11,
  IDENTIFY: 2,
  IDENTIFY_ACK: 12,
  JOIN_CHANNEL: 3,
  JOIN_CHANNEL_ACK: 13,
  LEAVE_CHANNEL: 4,
  LEAVE_CHANNEL_ACK: 14,
  STATE_UPDATE: 5,
  STATE_UPDATE_ACK: 15,
  PRESENTER: 6,
  PRESENTER_ACK: 16,
  VIEWER: 7,
  VIEWER_ACK: 17,
  ICE_CANDIDATE: 8,
  ICE_CANDIDATE_ACK: 18,
  STOP: 9,
  STOP_ACK: 19,
} as const;

export const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 1000,
  UNAUTHORIZED_ACCESS_TOKEN: 1001,
  UNAUTHORIZED_USER: 1002,
  INVALID_SERVER_ID: 1011,
  INVALID_CHANNEL_ID: 1012,
  INVALID_REQUEST_OPERATION: 1013,
  DUPLICATE_SERVER_DESTINATION: 1021,
  DUPLICATE_CHANNEL_ENTRY: 1022,
  DUPLICATE_CHANNEL_EXIT: 1023,
  WRONG_ACCESS_INACTIVE_USER: 1031,
  WRONG_ACCESS_INACTIVE_SERVER: 1032,
  WRONG_ACCESS_INACTIVE_CHANNEL: 1033,
} as const;

export const RECONNECT_DELAY = 5000;